sudo: false
language: java
install: mvn install -DskipTests=true
script: mvn test
jdk:
  - oraclejdk8
  - oraclejdk9
notifications:
  webhooks:
    urls:
      - "https://webhooks.gitter.im/e/dd34d6121ff41a9f9501"
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always